### ISSUE TITLE
Can't find remote-viewer

### ISSUE THREAD

**Issue by kermitdafrog8** [nemuTUI/nemu#105]
When loading nemu it can't find /usr/bin/remote-viewer.  Not sure what dependency I am missing for that.

**Comment by 0x501D** [comment]
Install this:

```
[I] app-emulation/virt-viewer
     Available versions:  10.0_p20210730 ~11.0 {+libvirt sasl +spice +vnc vte}
     Installed versions:  10.0_p20210730(10:51:30 AM 05/04/2022)(spice vnc -libvirt -sasl)
     Homepage:            https://virt-manager.org/
     Description:         Graphical console client for connecting to virtual machines
```

Or if you do not wanna to connect to VM via SPICE protocol just edit `.nemu.cfg`
```
spice_bin = /dev/null
```

**Comment by kermitdafrog8** [comment]
That fixed that error thanks.  Now I have a new error.

**Comment by 0x501D** [comment]
> That fixed that error thanks. Now I have a new error.

Please describe it.

**Comment by kermitdafrog8** [comment]
Says "Error opening terminal: linux."

**Comment by 0x501D** [comment]
> Says "Error opening terminal: linux."

Need more data:
Linux distro,  nemu --version

**Comment by kermitdafrog8** [comment]
Slackware64 --current
nEMU v3.0.0
 + VNC
 + SPICE
 + OVF import
 - SVG map
 + Link alt names
 + D-Bus support
 - Remote control

**Comment by kermitdafrog8** [comment]
Recompiled without any extra cmake flags beside INSTALL_PREFIX and BUILD_TYPE.  Seems to work now.
