### ISSUE TITLE
prob build on Opensuse

### ISSUE THREAD

**Issue by ljoli** [nemuTUI/nemu#158]
Hello,

I am on  **openSUSE Leap 15.4** and i would build  nemu on my OS.
But i have some errors : 

> cd build/
> cmake -G Ninja .. -DNM_WITH_NETWORK_MAP=ON -DNM_WITH_DBUS=ON -DNM_WITH_REMOTE=ON
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "XX/nemu/build/CMakeFiles/CMakeOutput.log".

How can build correctly ?

**Comment by 0x501D** [comment]
`sudo yum -y install ninja-build`

Just install ninja.

**Comment by ljoli** [comment]
Hi @0x501D 

I am on  rpm base distribution : openSUSE Leap 15.4 but I have no yum package manager.

I use **zypper** from command line for manage my distro.

And I can't find the package `ninja-build`. 

-- 

After some investigations, I found all the packages necessary : 
```
ninja
gcc
ncurses-devel
libusb
libusb-1_0-devel
sqlite3
sqlite3-devel
systemd-devel
libjson-c-devel
libxml2-devel
libarchive-devel
graphviz-devel
dbus-1-devel
libopenssl-devel
gettext-tools
```

And I follow the instructions on README_build  : 
cd nemu
mkdir build && cd build
cmake -G Ninja .. -DNM_WITH_NETWORK_MAP=ON -DNM_WITH_DBUS=ON -DNM_WITH_REMOTE=ON
cmake --build .

=> the binary nemu is done
