### ISSUE TITLE
Web service on VM accessible from the host?

### ISSUE THREAD

**Issue by ThalesC** [nemuTUI/nemu#161]
Hi, is there a simple way to create a vm with a web service accessible from the host machine?

After some search, I found that I should create a bridge interface and set some extra arguments on the startup command. 

I managed to start a bridge interface named `virbr0` using `libvirt` (I guess? just ran *libvirtd* on another terminal and it appeared) and set the `allow virbr0` entry on `/etc/qemu/bridge.conf` like so:

```
# This should have the following permissions: root:qemu 0640

# Allow users in the "qemu" group to add devices to "br0".
#allow br0
allow virbr0

# Uncomment the following line to allow users in the "bob"
# group to have permissions defined in it, iff it has the
# following permissions: root:bob 0640
#include /etc/qemu/bob.conf
```
I could then connect to a web service on the guest os when I started the vm using the following extra arguments:

```
# e - vm settings tab
Extra QEMU args: -netdev bridge,id=hn0,br=virbr0 -device virtio-net-pci,netdev=hn0,id=nic1
```

I'm a noob in QEMU, my first hands-on experience with it was through nemuTUI, so maybe I'm missing something regarding QEMU itself.

**Comment by ThalesC** [comment]
Ok, I'm not a complete noob anymore, did more research on QEMU and libvirt.

After creating a bridge interface, with either `libvirt` or `brctl`, I managed to create a workflow to do what I described on this issue, but I still need (I guess) to use the `Extra QEMU args` entry to achieve this.

Also, I'm using the `-nic` flag now, it does the same as before but using a single flag:
```
# e - vm settings tab
Extra QEMU args: -nic bridge,br=virbr0,model=virtio-net-pci,mac=XX:XX:XX:XX:XX:XX,id=nic1
```
For future reference: the `mac` is set so the dhcp can give different IPs to vm guests

That being said, is there a way to do this without the need to use the `Extra QEMU args` entry?

**Comment by 0x501D** [comment]
Hello, you can use portfwd feature with usernet enables or: disable usernet, set network inside guest and host interface with same subnetwork IP address. QEMU uses macvtap+veth to create virtual networks, this feature has one insufficient: host cannot communicate with guest, but guests can reach each other and external networks via host.

**Comment by ThalesC** [comment]
Yup, usernet does it!

Now I'm thinking about the usage of bridge interfaces, as described on my last comment, within nemu, but I'll open another issue (if necessary) after learning more.

Thanks!
