### ISSUE TITLE
Is libudev really required?

### ISSUE THREAD

**Issue by MajliTech** [nemuTUI/nemu#162]
Hello, 
I would like to build this under Termux. Hoverer, this requires UDev, which is not available there. Will there  be a way to disable USB connections to virtual machine with [this](https://github.com/nemuTUI/nemu/wiki/Building-from-sources#possible-options)?

Thanks.

**Comment by grafin** [comment]
There is currently no flag to disable usb support. But it is disabled during FreeBSD build. So I think it is not complicated to add such a flag. I will try to do it
