### ISSUE TITLE
Error when starting Nemu on ArchLinux

### ISSUE THREAD

**Issue by varaskkar** [nemuTUI/nemu#166]
In terminal, when I write "nemu" to run it, it shows the following:

> cfg: /usr/bin/remote-viewer: No existe el fichero o el directorio

I checked and I don't have the "remote-viewer" package in the /usr/bin path.

It seems that nemu didn't install the package "libvirt-vnc-viewer" and when I try to install it manually by AUR [it throws error](https://aur.archlinux.org/packages/libvirt-vnc-viewer) 

I'd like to try nemu but I don't know what else I could do if the package I need is not available through my distro.

**Comment by 0x501D** [comment]
Hi. nemu supports two graphical protocols: VNC and SPICE.
By default nemu uses SPICE: `.config/nemu/nemu.cfg`
```ini
[viewer]
# default protocol (1 - spice, 0 - vnc)
spice_default = 1
```

You can install any vnc-client (`tigervnc` for example has a vnc client) and setup nemu to use it. Example:
```ini
[viewer]
# default protocol (1 - spice, 0 - vnc)
spice_default = 0

# vnc client path.
vnc_bin = /usr/bin/vncviewer

# vnc client args (%t - title, %p - port)
vnc_args = :%p

# spice client path
spice_bin = /dev/null
```

**Comment by varaskkar** [comment]
It worked wonders, a thousand thanks, it was easier than I thought it'd be!
