### ISSUE TITLE
Improve exporting network map to svg

### ISSUE THREAD

**Issue by 0x501D** [nemuTUI/nemu#24]
Make exporting non-linear. Big maps now look awful and unreadable.

**Comment by grafin** [comment]
Right now it's like this:
![network](https://user-images.githubusercontent.com/426722/73256573-34534a00-41d3-11ea-893f-0b19530debb8.png)

**Comment by grafin** [comment]
Much better now
![all](https://user-images.githubusercontent.com/426722/74443300-fec18880-4e83-11ea-9edd-646a462da235.png)
