### ISSUE TITLE
Fix CMakeLists.txt for packaging

### ISSUE THREAD

**Issue by matthiasbeyer** [nemuTUI/nemu#37]
Hi,

I tried to package nemu, but I had problems doing so. Someone indicated that this happens due to your CMakeLists.txt here: https://github.com/NixOS/nixpkgs/pull/82004

Would be nice if you could fix it (whatever that means, I don't know how to write CMakeLists.txt files...)

**Comment by grafin** [comment]
Yeah, our CMakeLists definitely needs rework, I'll try to dig into this ASAP
