### ISSUE TITLE
Can this software run on the arrch64 hardware architecture

### ISSUE THREAD

**Issue by tiankangbo2019** [nemuTUI/nemu#39]
Can this software run on the arrch64 hardware architecture？

**Comment by grafin** [comment]
As far as I know it should, but no one tested it. If you run into any problems - feel free to ask, I'll try to help.

**Comment by tiankangbo2019** [comment]
Thank you. I will conduct a test on the arm architecture machine. If there is any problem, I will contact you.

**Comment by tiankangbo2019** [comment]
Hello, when I tested nemu on the arch64 hardware system, there were some display and input problems. For example, when importing image

**Comment by tiankangbo2019** [comment]
Hello Boris, when I tested nemu on the arch64 hardware system, there were some display and input problems. For example, when importing image
            



    


            On 06/10/2020 14:37, Boris Stepanenko wrote: 
As far as I know it should, but no one tested it. If you run into any problems - feel free to ask, I'll try to help.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nemuTUI/nemu/issues/39#issuecomment-641759970",
"url": "https://github.com/nemuTUI/nemu/issues/39#issuecomment-641759970",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by grafin** [comment]
Hello. Sorry for not replying for so long. I've reworked ncurses form handling in #67. I would appreciate if you test  [dynamic_forms](https://github.com/nemuTUI/nemu/tree/dynamic_forms) branch on aarch64.

**Comment by grafin** [comment]
I've tested nemu 3.0.0-RC0 on aarch64 (in virtual machine on x86_64) it looks like it works fine. If there are any problems on real hardware - feel free to open new issue.
