### ISSUE TITLE
Source compilation problems

### ISSUE THREAD

**Issue by tiankangbo2019** [nemuTUI/nemu#40]
When I tried to compile the source code, some undefined fields or functions appeared, and I didn't find the specific reason.

example:

nm_vm_snapshot.c:(.text+0x12b): undefined reference to `new_field'
nm_vm_snapshot.c:(.text+0x150): undefined reference to `new_field'
nm_vm_snapshot.c:(.text+0x173): undefined reference to `field_opts_off'
nm_vm_snapshot.c:(.text+0x17a): undefined reference to `TYPE_ENUM'
nm_vm_snapshot.c:(.text+0x194): undefined reference to `set_field_type'
nm_vm_snapshot.c:(.text+0x1a9): undefined reference to `set_field_buffer'

Why does it appear, for example “TYPE_ENUM” has no fields defined

**Comment by grafin** [comment]
@tiankangbo2019 Were you able to solve the problem yourself, or it needs to be investigated?

**Comment by tiankangbo2019** [comment]
Thank you for your email. I have solved the problem
