### ISSUE TITLE
Fix Cmake uninstall target not removing empty data directories

### ISSUE THREAD

**Issue by grafin** [nemuTUI/nemu#42]
After running make uninstall it only deletes files. Empty directories persist:

\# make uninstall
Scanning dependencies of target uninstall
-- Uninstalling /usr/local/bin/nemu
-- Uninstalling /usr/local/share/nemu/templates/config/nemu.cfg.sample
...
-- Uninstalling /usr/local/share/locale/ru/LC_MESSAGES/nemu.mo

\# tree /usr/local/share/nemu
/usr/local/share/nemu
├── qemu
│   ├── bin
│   ├── include
│   ├── libexec
│   └── share
│       ├── applications
│       ├── icons
│       │   └── hicolor
│       │       ├── 128x128
│       │       │   └── apps
│       │       ├── 16x16
│       │       │   └── apps
│       │       ├── 24x24
│       │       │   └── apps
│       │       ├── 256x256
│       │       │   └── apps
│       │       ├── 32x32
│       │       │   └── apps
│       │       ├── 48x48
│       │       │   └── apps
│       │       ├── 512x512
│       │       │   └── apps
│       │       ├── 64x64
│       │       │   └── apps
│       │       └── scalable
│       │           └── apps
│       └── qemu
│           ├── firmware
│           ├── keymaps
│           └── vhost-user
├── scripts
└── templates
    └── config

33 directories, 0 files

**Comment by grafin** [comment]
Should we close this on with #wontfix?
![image](https://user-images.githubusercontent.com/426722/121864514-a7e0f300-cd05-11eb-86de-5ea1faf3b268.png)

**Comment by 0x501D** [comment]
yep
