### ISSUE TITLE
Please enable discard support

### ISSUE THREAD

**Issue by holgersson32644** [nemuTUI/nemu#49]
Hi,
adding discard=on to the device options of qemu brings discard/trim support. When fstrim is called inside the VM the host get's notified about freed disk space and therefor images can actually get smaller again. This works for qcow2 images, for other types I don't know, but nemu uses qcow2 anyway.
There is a a security implication with discard and LUKS, but the guest has to trust the VM host anyways.

So: Please add discard support!

Kind regards,
Nils

**Comment by 0x501D** [comment]
Hello, good idea. I will add this option soon.
