### ISSUE TITLE
Please add support for user networking

### ISSUE THREAD

**Issue by holgersson32644** [nemuTUI/nemu#50]
Hi,
I do prefer user networking as I get a NAT'ed network with a DHCP setup working out of the box.
Currently I have to disable networking in nemu and add flags manually like
```-device virtio-net,netdev=VM1 -netdev user,id=VM1```
and it would be great to enable it directly through a checkbox in nemu, so I'd like to request that feature.

Kind regards,
Nils

**Comment by 0x501D** [comment]
Do you wanna check box that will replace?:
-device virtio-net-pci,mac=de:ad:be:ef:02:27,netdev=netdev0 -netdev tap,ifname=vm-deadbeef0227,script=no,downscript=no,id=netdev0,vhost=on
with:
-device virtio-net-pci,mac=de:ad:be:ef:02:27,netdev=netdev0 -netdev user,id=netdev0

In this case VM can get DHCP address from QEMU internal DHCP server, yes.
Please tell me what use case this feature will cover?

**Comment by holgersson32644** [comment]
Hi, yes. My use case is just to avoid more complex tap networking and get a network that works out of the box. Maybe it's even just an issue on my machine or I just don't see an already implemented way.

**Comment by 0x501D** [comment]
OK, I will research this feature and add it to nemu.
