### ISSUE TITLE
config menus are hardly readable when the cursor is a _ (instead of | oder ⌷)

### ISSUE THREAD

**Issue by holgersson32644** [nemuTUI/nemu#51]
Hi,
my terminal's cursor is a blinking underscore (_), which is hardly readable inside the nemu config UI.
Can you somehow work around that in curses, e.g. force another cursor there?
Would be great!

Kind regards,
Nils

**Comment by 0x501D** [comment]
Hello, ncurses library has no support for saving/changing/restore of cursor shape.
This can be done only with escape sequences manipulation.
In theory we can add this as feature like "vim" does:
https://vim.fandom.com/wiki/Change_cursor_shape_in_different_modes.

So we can add some parameters in config like this: cursore_blink = 0|1, cursore_shape_type.
Also we need to restore initial cursor settings after nemu is exited. So maybe we can implement this feature.

**Comment by grafin** [comment]
3fd7b59e7e0fd5a096046fac64d310227a3baf0a Used DECSCUSR VT520 escape sequence. Should work as requested. On some VTEs may leave cursor as blinking block after exit, if those VTEs don't support changing cursor type to user default on DECSCUSR 0.

**Comment by holgersson32644** [comment]
Thanks a lot, this works fine now!

**Comment by 0x501D** [comment]
This is good, but we should make this action configurable.

**Comment by grafin** [comment]
b81fb147bcdd7e1bb229006812a047de5216fba6 and d0ef4af0ea7f55da35e5cda22b5faa1231e6180a make an optional parameter in nemu config file. Should be closed for good.
