### ISSUE TITLE
Update Wiki for project

### ISSUE THREAD

**Issue by grafin** [nemuTUI/nemu#6]
**[Original report](https://bitbucket.org/PascalRD/nemu/issue/17) by Boris Stepanenko (Bitbucket: [GrafIn1992](https://bitbucket.org/GrafIn1992), ).**

----------------------------------------

Russian wiki page needs to be updated.

English wiki page should be made.

**Comment by grafin** [comment]
We need:
1. Make a list of build dependencies
2. Make a list of run dependencies
3. Write an INSTALL how to
4. Maybe write USAGE how to

**Comment by 0x501D** [comment]
Also create man(1) page...

**Comment by grafin** [comment]
LGTM:) maybe one day I'll add additional pages
