### ISSUE TITLE
Support for running UEFI VM's

### ISSUE THREAD

**Issue by henriquehbr** [nemuTUI/nemu#60]
I'm not sure if this already implemented, but is it possible to launch a virtual machine with UEFI instead of BIOS? if not, would you consider a good idea putting it into the project?

It could be something like the [`run_archiso`](https://github.com/archlinux/archiso/blob/master/scripts/run_archiso.sh) script created by `archiso` package which gives you the option to pass the `-u` flag to set the boot type to UEFI, but added as a toggleable option on the TUI

**EDIT:** Under the hood, basically what it does is to get the appropriate `OVMF.fd` (32 or 64 bits) file from the `edk2-ovmf` package and pass it to `qemu` through the `--bios` flag

**Comment by grafin** [comment]
It's possible, in boot configuration of created VM (push "b" in main screen) you can set BIOS path to your OVMF.fd path and it should work.
![image](https://user-images.githubusercontent.com/426722/120434325-ff39a780-c384-11eb-9c5e-7f877968e3ae.png)

**Comment by henriquehbr** [comment]
Amazing! thanks for the response, i'm going to try it out now

Keep up the great job with the project, it's really relieving not having to type those hunderds of CLI arguments again

**Comment by 0x501D** [comment]
I'm using extra args to boot with OVMF:
`if=pflash,format=raw,readonly,file=/home/void/iso/OVMF_CODE.secboot.fd -drive if=pflash,format=raw,file=/home/void/iso/OVMF_VARS.secboot.fd`

**Comment by grafin** [comment]
@0x501D I think we should close this issue, because there is BIOS option already. I created a new issue for pflash drives support.
