### ISSUE TITLE
Publish on the AUR

### ISSUE THREAD

**Issue by henriquehbr** [nemuTUI/nemu#61]
Do you have any plans on publishing this package on the Arch User Repository (AUR), in order to ease the installation process for Arch users? if you're willing to, i can help with that

**Comment by grafin** [comment]
PKGBUILD file has already been added (https://github.com/nemuTUI/nemu/pull/47). If you can help us publish it in AUR, we would appreciate it. For details on PKGBUILD you should contact @MaksVal. If any changes are needed - feel free to send us pull requests.

**Comment by MaksVal** [comment]
Hmmm, unfortunately
 @haawda (https://aur.archlinux.org/account/haawda) is the owner of the package in AUR: https://aur.archlinux.org/packages/nemu-git/ He won’t give it to me to maintain.

**Comment by MaksVal** [comment]
#63

**Comment by stefanhusmann** [comment]
Both nemu and nemu-git are in AUR for long, so I do not know what you are talking about. I won't give maintainership to MaksVal because he or she is constantly misusing the out-of-date-flag in AUR.

**Comment by MaksVal** [comment]
@stefanhusmann  I just took a copy of @haawda and updated the version and repository.
If you can help, I ready to fix this mistake. What's it called, that flag?

**Comment by grafin** [comment]
As far as I understand, there is no issue with AUR package. Thread closed.
