### ISSUE TITLE
Database version is not up do date

### ISSUE THREAD

**Issue by macpijan** [nemuTUI/nemu#68]
I have simply installed nemu 2.6.0 from package for Ubuntu 20.04.

When trying to start `nemu` (after answering some configuration questions):

```
$ nemu
Database version is not up do date. I will try to update it.
Cannot update database
```

```
$ nemu --version
nEMU v2.6.0
 + VNC
 + SPICE
 - Snapshots
 + OVF import
 - SVG map
 - Link alt names
 - D-Bus support
 ```
 
 The DB in config is set to `/home/maciej/.nemu.db`.
 
 The DB was initialized as an empty file:
 
```
$ ls -la ~/.nemu.db 
-rw-r--r-- 1 maciej maciej 0 cze 14 21:46 /home/maciej/.nemu.db
```

**Comment by grafin** [comment]
Have you tried deleting database and trying to start nemu again?
I will try to reproduce this tomorrow, are those steps correct:
1. Install Ubuntu 20.04
2. Install nemu 2.6.0 from Debian package
3. Try to start nemu "$ nemu"
?

**Comment by macpijan** [comment]
1. Yes:

```
$ rm ~/.nemu.db
$ nemu
Database version is not up do date. I will try to update it.
Cannot update database

$ ls -la ~/.nemu.db
-rw-r--r-- 1 maciej maciej 0 cze 14 21:59 /home/maciej/.nemu.db
```

2. Yes (although it's not clean OS).

**Comment by grafin** [comment]
Ok, will try with clean OS. If the problem reproduces I'll investigate it. If not, I'll ask for more info about your system.

**Comment by 0x501D** [comment]
I can confirm it.

**Comment by 0x501D** [comment]
btw, in master we got another error:
nm_db_select: database error: database is locked.

steps to reproduce:
nemu-daemon must be stopped,
rm db, cfg
run nemu.

but after error db created successfully and nemu starts without problem.
now will test with ubuntu.

**Comment by 0x501D** [comment]
I think we need use sqlite3_open_v2() with one of this flags:

```
SQLITE_OPEN_NOMUTEX
The new database connection will use the "multi-thread" threading mode. This means that separate threads are allowed to use SQLite at the same time, as long as each thread is using a different database connection.
SQLITE_OPEN_FULLMUTEX
The new database connection will use the "serialized" threading mode. This means the multiple threads can safely attempt to use the same database connection at the same time. (Mutexes will block any actual concurrency, but in this mode there is no harm in trying.)
```

**Comment by 0x501D** [comment]
Cannot reproduce on Ubuntu 20.04 clean install with master and v2.6.0 tag.
Please specify sqlite3 version installed on your system.

**Comment by 0x501D** [comment]
but  on Ubuntu 20.04 if no db exists nemu daemon falls with error: database is locked.
cannot reproduce null size db file, but problem exists.

**Comment by macpijan** [comment]
I will try to check in the evening

**Comment by 0x501D** [comment]
[](url)

**Comment by 0x501D** [comment]
Need more testing. Connections to DB reworked 7198e945ab06518fef448b171e5e8bee1b736e51

**Comment by macpijan** [comment]
```
sqlite3 --version
3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837balt1
```

**Comment by macpijan** [comment]
Somewhat different errors when building from master (https://github.com/nemuTUI/nemu/commit/eeb1634bd1547aa34037cebe2c6667435258ec48).

Maybe I'm missing something obvious?

```
$ ./nemu --version
nEMU v2.6.0-97-geeb1634bd154
 + VNC
 + SPICE
 + OVF import
 - SVG map
 - Link alt names
 - D-Bus support
 - Remote control

$ ./nemu
Config file "/home/maciej/.nemu.cfg" is not found.
You can copy example from:
/usr/local/share/nemu/templates/config/nemu.cfg.sample
and edit it manually or let the program generate it.

Generate cfg? (y/n)
> y
VM storage directory [default: /home/maciej/nemu_vm]
>
VM settings database path [default: /home/maciej/.nemu.db]
>
VNC client path (enter "/bin/false" if you connect other way) [default: /usr/bin/vncviewer]
>
VNC client arguments [default: :%p]
>
SPICE client path(enter "/bin/false" if you connect other way) [default: /usr/bin/remote-viewer]
>
SPICE client arguments [default: --title %t spice://127.0.0.1:%p]
>
Path to directory, where QEMU binary can be found [default: /usr/bin]
>
QEMU system targets list, separated by comma [default: ppc64,ppc,ppc64le,i386,x86_64,x86_64-spice]
>
nm_mon_start: execlp error: No such file or directory
nm_mon_start: failed to start daemon

$ ./nemu
nm_mon_start: execlp error: No such file or directory
nm_mon_start: failed to start daemon
```

**Comment by macpijan** [comment]
Ok, I guess I need to start daemon first with `./build/nemu -d` and then start the client itself with `./build/nemu`? Then the `master` works for me - at least I can start it.

**Comment by grafin** [comment]
Looks like nemu tries to start daemon via "/usr/local/bin/nemu" or where the INSTALL_PATH was, and fails to do so, because it wasn't installed. Should get fixed when it'll be installed from updated deb package.

**Comment by grafin** [comment]
UPD. You can try adding path to ./build directory to your $PATH. After that try killing all nemu procceses (including nemu --daemon) and starting nemu again, it should work and start daemon automatically.

**Comment by 0x501D** [comment]
Cannot reproduce. Will be reopened if someone catch this bug again.

**Comment by papanito** [comment]
I have the same issue right now

```
$ nemu --version
nEMU v3.5.0
 + OVF import
 + SVG map
 + Link alt names
 + D-Bus support
 + Remote control
 + USB Support
```

I am on nixos.
