### ISSUE TITLE
nm_net_manage_tap: ioctl(TUNSETIFF)

### ISSUE THREAD

**Issue by Kabouik** [nemuTUI/nemu#74]
First, thank you for this great program. Really happy to find a TUI interface for QEMU.

I installed (as in `I` in nemu, I didn't boot it yet) a new VM in nemu but I am getting `nm_net_manage_tap: ioctl(TUNSETIFF): Operation not permitted` every time I try to run it with `r`. I am not sure where is the issue.

I could try running `nemu` as root, see if it helps, but this would imply making a new configuration file in `/root/.nemu.cfg` and running nemu as root all the time, which is not desirable.

**Comment by grafin** [comment]
Hi, try looking at https://github.com/nemuTUI/nemu/wiki/Running-as-non-root it should work, if it doesn't, or you'll have any other questions, feel free to ask.

**Comment by Kabouik** [comment]
Thank you, that worked! I am sorry I missed the wiki before posting here. I just add to use the manual settings instead of the script (it was only in the git repository, but not in ` /usr/share` , and I had ot change the path to `nemu`: `setcap CAP_NET_ADMIN=ep /usr/local/bin/nemu`).

I may still have an issue to display the VM when it is running, but this may also just be that I am not sure yet how to use `nemu`. It is late so I'll check later and read more documentation.
