### ISSUE TITLE
Add musl build check to drone

### ISSUE THREAD

**Issue by grafin** [nemuTUI/nemu#88]
After we close #87 we should add step for building nemu in alpine container, to check that further commits wont break it.

**Comment by dm9pZCAq** [comment]
some projects uses ubuntu for this, maybe this is easier

+ [gitui](https://github.com/extrawurst/gitui/blob/3b5d43ecb28d4846e4f5d16b3fa68ab63fd776c9/.github/workflows/ci.yml#L93-L94)
  + [runs](https://github.com/extrawurst/gitui/runs/3505812583)

**Comment by grafin** [comment]
92358bfcca5f94011f2c8d10d825a2130b1404c5
