### ISSUE TITLE
Fix CI/CD

### ISSUE THREAD

**Issue by grafin** [nemuTUI/nemu#94]
1) https://github.blog/changelog/2021-09-21-codeql-runner-deprecation/
2) Update deb package build somehow. Maybe we should move deb and rpm builds to our own CI/CD server...

**Comment by grafin** [comment]
3. add https://github.com/IntelLabs/control-flag/

**Comment by 0x501D** [comment]
Will use packpack for debs.

**Comment by 0x501D** [comment]
* debs updated

**Comment by 0x501D** [comment]
codeql is fixed in docker, so we can skip updating.
