### ISSUE TITLE
Create tests and use Coverity Scan

### ISSUE THREAD

**Issue by 0x501D** [nemuTUI/nemu#96]
We can use something like this:  https://www.drmaciver.com/2015/05/using-tmux-to-test-your-console-applications/

**Comment by grafin** [comment]
Totally agree, we can start by writing test for strings, vectors and other custom structures and their methods. For that we can use some testing framework like https://libcheck.github.io/check/

**Comment by 0x501D** [comment]
OK, I'll take this

**Comment by 0x501D** [comment]
#97

**Comment by ligurio** [comment]
> Totally agree, we can start by writing test for strings, vectors and other custom structures and their methods. For that we can use some testing framework like https://libcheck.github.io/check/

I strongly recommend taking a look on CMocka for unit testing.
https://cmocka.org/

**Comment by 0x501D** [comment]
Thanks, I'll take a look at the cmoka.
